datamole-ai/edvart

- docs/Makefile
The variable `SPHINXPROJ` is unused, and its value is wrong.
> build: Remove unused variable in `Makefile`.

- .github/workflows/test.yaml
With the squash workflow, pull requests are squashed and the PR title is used as the commit message in main. Therefore, only the PR title needs to be conventional.
> ci: Adapt to squash workflow

- edvart/data_types.py
- tests/test_data_type_inference.py
- tests/test_utils.py
> feat: Add missing data type

- .github/workflows/publish.yaml
The `poetry version` command was missing. This results in version `0.0.0` always being published, which fails, see for example
https://github.com/datamole-ai/edvart/actions/runs/5680069282/job/15393445320
> ci: set package version before publishing to PyPI

- edvart/plots.py
matplolib `Axes.set_xlabel` does not support `None` as the first parameter. https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.set_xlabel.html
> fix: method not accepting `None` being called with `None`.

- edvart/plots.py
The scatter plot has an interactive and a non-interactive version. The top-level function now just deciedes which of the two new functions to call.
> refactor: split `scatter_plot_2d` into 2 functions.

- .github/workflows/publish.yaml
Avoid releasing many intermediate versions with incomning breaking changes.
> ci: temporarily disable publishing

- api-example.md
- docs/advanced.rst
- docs/getting_started.rst
- edvart/__init__.py
- edvart/report.py
- tests/test_report.py
> feat!: Refactor `Report` into `Report` and `DefaultReport`.

- .github/workflows/publish.yaml
Publishing was temporarily disabled in 7c6ab67.
This keeps the publishing disabled but allows us to trigger it if needed.
> ci: publish on workflow_dispatch

- docs/advanced.rst
- edvart/__init__.py
- edvart/report.py
- edvart/report_sections/bivariate_analysis.py
- edvart/report_sections/dataset_overview.py
- edvart/report_sections/group_analysis.py
- edvart/report_sections/multivariate_analysis.py
- edvart/report_sections/section_base.py
- edvart/report_sections/table_of_contents.py
- edvart/report_sections/timeseries_analysis/autocorrelation.py
- edvart/report_sections/timeseries_analysis/boxplots_over_time.py
- edvart/report_sections/timeseries_analysis/fourier_transform.py
- edvart/report_sections/timeseries_analysis/rolling_statistics.py
- edvart/report_sections/timeseries_analysis/seasonal_decomposition.py
- edvart/report_sections/timeseries_analysis/short_time_ft.py
- edvart/report_sections/timeseries_analysis/stationarity_tests.py
- edvart/report_sections/timeseries_analysis/time_analysis_plot.py
- edvart/report_sections/timeseries_analysis/timeseries_analysis.py
- edvart/report_sections/umap.py
- edvart/report_sections/univariate_analysis.py
- tests/test_bivariate_analysis.py
- tests/test_group_analysis.py
- tests/test_multivariate_analysis.py
- tests/test_overview_section.py
- tests/test_report.py
- tests/test_timeseries_analysis.py
- tests/test_univariate_analysis_section.py
Closes https://github.com/datamole-ai/edvart/issues/65
> refactor: use Enum for verbosity

- edvart/report_sections/bivariate_analysis.py
- edvart/report_sections/dataset_overview.py
- edvart/report_sections/multivariate_analysis.py
- edvart/report_sections/timeseries_analysis/timeseries_analysis.py
These changes should have been made in commit 521ce53.
> refactor: use new Verbosity enum instead of int

- edvart/report.py
- edvart/report_sections/table_of_contents.py
- tests/test_report.py
By design it was possible to add table of contents multiple times.
The rendered report then contained multiple table of contents.
Having a separate argument for table of contents instead of having
it in sections list makes multiple calls of add_table_of_contents()
idempotent — always only one ToC is rendered in the end.
> feat: make addition of ToC idempotent

- edvart/report_sections/section_base.py
- tests/test_bivariate_analysis.py
- tests/test_group_analysis.py
- tests/test_multivariate_analysis.py
- tests/test_overview_section.py
- tests/test_timeseries_analysis.py
- tests/test_univariate_analysis_section.py
Having all values positive allows convenient constructs such as
`section_verbosity = section_verbosity or default_verbosity`,
where `section_verbosity` can be optional, i.e. `Verbosity | None`.
BREAKING CHANGE: Change Verbosity values. LOW is now 1 (was 0), MEDIUM
is 2 (was 1) and HIGH is 3 (was 2).
> feat!: change Verbosity enum values

- edvart/data_types.py
- edvart/report_sections/univariate_analysis.py
- tests/test_data_type_inference.py
> feat: Add `UNIQUE` data type

- edvart/report_sections/bivariate_analysis.py
The tight layout looks good and seaborn automatically switches to it anyways, which raises a warning.
> feat: Plot pairplot with tight layout.

- tests/test_data_type_inference.py
Silence a pandas warning about default dtype of empty DataFrame by explicitly specifying a dtype.
> test: Silence pandas warning.

- edvart/report.py
Fix a docstring regarding verbosity in `TimeSeriesReport` class. The change should have been made in https://github.com/datamole-ai/edvart/pull/81.
> docs: fix docstring

- edvart/report.py
Previously plotly plots would not be rendered in HTML exports.
> fix: set default plotly renderer when exporting to HTML

- edvart/report.py
- edvart/report_sections/timeseries_analysis/__init__.py
- edvart/report_sections/timeseries_analysis/time_series_line_plot.py
- edvart/report_sections/timeseries_analysis/timeseries_analysis.py
- tests/test_timeseries_analysis.py
The new name better describes the plot.
BREAKING CHANGE: The name of `edvart.report_sections.timeseries_analysis.TimeAnalysisPlot` was changed to `edvart.report_sections.timeseries_analysis.TimeSeriesLinePlot`.
Resolves #52.
> refactor!: Rename `TimeAnalysisPlot` to `TimeSeriesLinePlot`. 

- tests/test_bivariate_analysis.py
- tests/test_multivariate_analysis.py
- tests/test_timeseries_analysis.py
Fixed *verbosity* misspelled as *verobsity* in names of multiple tests.
> test: fix typos in the word "verbosity"

- edvart/report.py
- edvart/report_sections/dataset_overview.py
- tests/test_overview_section.py
*Occurence* is a misspelling.
BREAKING CHANGE: Class `edvart.report_sections.dataset_overview.ConstantOccurence` renamed to `ConstantOccurrence`.
BREAKING CHANGE: Parameter `verbosity_constant_occurence` of `edvart.report.ReportBase.add_overview` renamed to `verbosity_constant_occurrence`.
BREAKING CHANGE: Enum value `ConstantOccurence` of `edvart.report_sections.dataset_overview.Overview.OverviewSubsection` changed to `ConstantOccurrence`.
> refactor!: rename ConstantOccurence -> ConstantOccurrence

- edvart/report_sections/dataset_overview.py
Render constant in constant occurrence as italic instead of in quotes, which makes the value look like a string.
Resolves #57
> feat: render constant as italic

- edvart/report_sections/group_analysis.py
- edvart/report_sections/timeseries_analysis/seasonal_decomposition.py
- edvart/report_sections/timeseries_analysis/time_series_line_plot.py
- edvart/report_sections/univariate_analysis.py
> feat: replace warnings with markdown printouts

- .github/workflows/test.yaml
By default pull request triggers on event types `opened`, `reopened`, `synchronize`.
See https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request
Added also trigger on event type `edited`.
Resolves #87
> ci: run test workflow on PR edited

- README.md
The GitHub preview does not render Plotly interactive plots.
Resolves #85.
> docs: Link example notebook in nbviewer.org

- edvart/plots.py
- edvart/report_sections/multivariate_analysis.py
- edvart/report_sections/timeseries_analysis/time_series_line_plot.py
- edvart/utils.py
- tests/test_multivariate_analysis.py
- tests/test_utils.py
Resolves #25 
BREAKING CHANGE: function `edvart.utils.is_categorical` is removed. `edvart.data_types.is_categorical`
can be used instead, with similar behavior.
BREAKING CHANGE: Slightly changes behavior of column selection for some plots, e.g. parallel categories is now stricter in choosing which columns are considered as categorical.
> feat!: Remove `utils.is_categorical`

- docs/usage.rst
- edvart/report.py
- tests/test_report.py
This simplifies the code base and does not limit the usability.
The users might need a bit more code to use the `omit_columns` semantic
but it's IMHO not radical and maybe even more transparent.
Currently, users might be a bit confused whether `use_columns` or
`omit_columns` take precendence in cases like:
`.add_bivariate_analysis(use_columns=['a', 'b'], omit_columns=['b',
'c']`.
Should the resulting columns be `['a', 'b']` or just `['a']`?
Using just one argument makes it 100% clear.
BREAKING_CHANGE: `use_columns` and `omit_columns` parameters in report
classes are replaced by `columns` which has the same semantic as
`use_columns`.
E.g. call `.add_bivariate_analysis(omit_columns=['a'])` can be replaced
by `.add_bivariate_analysis(columns=set(df.columns) - {'a'})`
Closes #121
> refactor!: use `columns` arg instead of `use_columns` and `omit_columns`

- edvart/report_sections/multivariate_analysis.py
A categorical color column uses discrete colors. Treating a boolean color column as numeric means it uses a colorscale for values from 0 to 1 even though there are no values between 0 and 1.
> feat: treat boolean color column as categorical

- edvart/report_sections/bivariate_analysis.py
Old behavior: columns [a,b,c] specified -> get pairs [(a,b), (b,a), (a,c), (c,a), (b,c), (c,b)]
New behavior: get pairs ([a,b], [a,c], [b,c])
> feat: exclude swapped column pairs in contingency tables

- tests/__init__.py
The use of a non-interactive plotting backend prevents plots from being displayed in pop-up windows while running tests. The tests would previously block when a plot was displayed until the user closed it.
Resolves #31
> test: use non-interactive plotting backend

- edvart/report.py
- edvart/report_sections/bivariate_analysis.py
- edvart/report_sections/dataset_overview.py
- edvart/report_sections/group_analysis.py
- edvart/report_sections/multivariate_analysis.py
- edvart/report_sections/section_base.py
- edvart/report_sections/table_of_contents.py
- edvart/report_sections/timeseries_analysis/autocorrelation.py
- edvart/report_sections/timeseries_analysis/boxplots_over_time.py
- edvart/report_sections/timeseries_analysis/fourier_transform.py
- edvart/report_sections/timeseries_analysis/rolling_statistics.py
- edvart/report_sections/timeseries_analysis/seasonal_decomposition.py
- edvart/report_sections/timeseries_analysis/short_time_ft.py
- edvart/report_sections/timeseries_analysis/stationarity_tests.py
- edvart/report_sections/timeseries_analysis/time_series_line_plot.py
- edvart/report_sections/timeseries_analysis/timeseries_analysis.py
- edvart/report_sections/umap.py
- edvart/report_sections/univariate_analysis.py
- tests/test_bivariate_analysis.py
- tests/test_group_analysis.py
- tests/test_multivariate_analysis.py
- tests/test_overview_section.py
- tests/test_timeseries_analysis.py
- tests/test_univariate_analysis_section.py
This is a preparation for removing the paramter `df` from the constructors
of `GroupAnalysis` and `UnivariateAnalysis` sections, which currently store `df` in the class and use
it to decide the code to generate.
BREAKING CHANGE: method `add_cells` of every section has a new required parameter `df`.
> refactor!: Add parameter `df` to method `Section.add_cells`.

- .pylintrc
- edvart/report.py
- edvart/report_sections/group_analysis.py
- edvart/report_sections/univariate_analysis.py
- tests/test_group_analysis.py
- tests/test_univariate_analysis_section.py
BREAKING CHANGE: Parameter `df` is removed from constructors of `GroupAnalysis` and `UnivariateAnalysis`.
> refactor!: remove parameter `df` from section constructors

- edvart/report_sections/bivariate_analysis.py
A bug was introduced in #131, which caused columns not to be filtered if the parameter `columns` is specified resulting in useless contingency tables being generated.
To reproduce the previously existing bug:
```python
import edvart
dataset = edvart.example_datasets.dataset_titanic()
report = edvart.Report(dataset).add_bivariate_analysis(columns=['Age', 'Fare', 'Survided', 'Sex']).show()
```
The above example displays contingency tables for numeric columns `Age`, `Fare`, which are numeric and thus contain many unique, resulting in huge & useless contingency tables being displayed.
> fix: fix included columns in contingnecy tables

- edvart/report_sections/table_of_contents.py
> refactor!: make `TableOfContents` not inherit from `Section`

- edvart/pandas_formatting.py
pandas version ^1.5 is required, thus the code in no longer needed.
> chore: remove code for compatibility with pandas <1.4

- edvart/report_sections/bivariate_analysis.py
- edvart/report_sections/dataset_overview.py
- edvart/report_sections/multivariate_analysis.py
- edvart/report_sections/timeseries_analysis/timeseries_analysis.py
- tests/test_bivariate_analysis.py
- tests/test_multivariate_analysis.py
- tests/test_overview_section.py
- tests/test_timeseries_analysis.py
Previously, the subsections enum (which is part of the section class) was not being imported.
> fix: fix imports when non-default subsections are specified

- edvart/report_sections/timeseries_analysis/autocorrelation.py
- edvart/report_sections/timeseries_analysis/boxplots_over_time.py
- edvart/report_sections/timeseries_analysis/fourier_transform.py
- edvart/report_sections/timeseries_analysis/rolling_statistics.py
- edvart/report_sections/timeseries_analysis/seasonal_decomposition.py
- edvart/report_sections/timeseries_analysis/short_time_ft.py
- edvart/report_sections/timeseries_analysis/stationarity_tests.py
- edvart/report_sections/timeseries_analysis/time_series_line_plot.py
- tests/test_timeseries_analysis.py
Continuation of #142 for timeseries analysis.
BREAKING CHANGE: Renamed top-level functions in `edvart.report_sections.timeseries_analysis`: added prefix `show_` (e.g. `edvart.report_sections.timeseries_analysis.timeseries_analysis` -> `edvart.report_sections.timeseries_analysis.show_timeseries_analysis`)
> refactor!: add prefix `show_` to functions matching module name

- edvart/report.py
Preparatory commit for testing of exported code being able to execute (#8).
> refactor: move default imports to a constant

- edvart/report_sections/timeseries_analysis/autocorrelation.py
The statsmodels function requires that `lags` is at most half of the length of the sample. However, by default the function may choose a value which does not satisfy this requirement.
> fix: limit default `lags` in autocorrelation

- edvart/report_sections/timeseries_analysis/boxplots_over_time.py
The parameter adds the ability to use custom imports when a custom grouping function is used.
> feat: add parameter `BoxplotsOverTime.group_function_imports`

- edvart/report.py
- edvart/report_sections/bivariate_analysis.py
- edvart/report_sections/dataset_overview.py
- edvart/report_sections/multivariate_analysis.py
- edvart/report_sections/timeseries_analysis/__init__.py
- edvart/report_sections/timeseries_analysis/timeseries_analysis.py
- tests/test_bivariate_analysis.py
- tests/test_multivariate_analysis.py
- tests/test_overview_section.py
- tests/test_timeseries_analysis.py
> refactor!: move subsection enums outside section classes

- edvart/data_types.py
- edvart/example_datasets.py
- edvart/pandas_formatting.py
- edvart/plots.py
- edvart/report.py
- edvart/report_sections/bivariate_analysis.py
- edvart/report_sections/code_string_formatting.py
- edvart/report_sections/group_analysis.py
- edvart/report_sections/multivariate_analysis.py
- edvart/report_sections/timeseries_analysis/__init__.py
- edvart/report_sections/timeseries_analysis/autocorrelation.py
- edvart/report_sections/timeseries_analysis/boxplots_over_time.py
- edvart/report_sections/timeseries_analysis/fourier_transform.py
- edvart/report_sections/timeseries_analysis/rolling_statistics.py
- edvart/report_sections/timeseries_analysis/seasonal_decomposition.py
- edvart/report_sections/timeseries_analysis/short_time_ft.py
- edvart/report_sections/timeseries_analysis/stationarity_tests.py
- edvart/report_sections/timeseries_analysis/time_series_line_plot.py
- edvart/report_sections/timeseries_analysis/timeseries_analysis.py
- edvart/report_sections/univariate_analysis.py
- edvart/utils.py
The comments are redundant and most of them misleading as they referred
to modules as packages.
> docs: remove module comments

- edvart/data_types.py
Pandas 2.x changed the behavior of `pd.api.types.is_string_dtype`. Previously
it would return `True` for `object` dtype, now it returns `False`.
> fix: data type inference for string types in pandas 2

- edvart/data_types.py
- edvart/report_sections/dataset_overview.py
Pandas 2.0 `pd.to_datetime` warns upon unsuccessful inference of date format.
The warning is unwanted since we use the success/failure of conversion to datetime to determine
whether a column is a datetime, i.e. knowingly call the function on data which might not contain
datetimes.
> fix: suppress warnings in data type inference

- pyproject.toml
isort is a dependency of edvart with #144
Resolves #182
> fix: move isort from dev dependencies to main dependencies

- .github/workflows/test.yaml
- pyproject.toml
With #159 and #162, we have added more and longer-running tests, which results in the test suite taking over 10 minutes to complete. Since the tests are independent of each other, they can be run in parallel.
> ci: execute tests in parallel

- edvart/report_sections/dataset_overview.py
In the missing values section, there is a horizontal bar plot already, which displays all the necessary information.
The vertical bar plot is redundant, thus disable it by default.
> feat: disable missing bar plot by default

- cliff.toml
The author name does not bring much value in the changelog. A GitHub handle
could be more useful, but git cliff does not support it.
> docs: remove author name from changelog

- edvart/report_sections/multivariate_analysis.py
The first and tick labels for categorical columns would previously be aligned to the ends of the colorbar. This PR ensures that the edge tick labels are aligned to the center, same as the non-edge ones are aligned.
> fix: fix alignment of colorbar labels for categorical color column in parallel coordinates & parallel categories sections

- edvart/report_sections/multivariate_analysis.py
Previously, categorical color columns (e.g. with values `{1,2,3}`, such as `edvart.example_datasets.dataset_auto()["origin"]`)
would be treated as numeric in multivariate analysis parallel coordinates & parallel categories sections, i.e. a continuous color scale would be used.
> feat: treat categorical color column which is also numeric as categorical in parallel coordinates & parallel categories

- pyproject.toml
Lower versions of pyarrow have a critical security issue. See https://github.com/advisories/GHSA-5wvp-7f3h-6wmm
> fix: upgrade pyarrow dependency

- .github/workflows/publish.yaml
In #202, trusted publishing to PyPI was introduced, requiring permission id-token: write.
However, all permissions were granted to the CI, which is not necessary. This PR restricts
the workflow permissions to those which are necessary.
> ci: remove unnecessary publish workflow permissions

- tests/test_multivariate_analysis.py
- Fix umap being imported when the extras is not installed, causing the test to fail
- Remove unused imports
> test: fix imports in multivariate analysis

- .github/workflows/test.yaml
- pyproject.toml
NOTE: extras umap-learn is not supported in Python 3.12 since umap-learn does not currently support Python 3.12.
BREAKING CHANGE: Support for Python 3.8 is dropped.
> feat!: add initial support for python 3.12

- .github/workflows/publish.yaml
See previously failed publish job: https://github.com/datamole-ai/edvart/actions/runs/8277873764/job/22649779315
> ci: fix missing token permissions required for publishing
